config/routes.rb
Rails.application.routes.draw do
  devise_for :users

 devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'sign_up', to: 'devise/registrations#new', as: :sign_up
  end

  root to: 'home#index'
  
  resources :users, only: [:index, :show, :new, :create] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/comments.rb
class Comments < ApplicationRecord
    belongs_to :users
    belongs_to :posts
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user_and_post, only: %i[new create]
  before_action :find_comment, only: [:destroy]
  before_action :authorize_comment, only: [:destroy]

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = @user

    if @comment.save
      flash[:success] = 'Comment was successfully created.'
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@comment.post), notice: 'Comment was successfully destroyed.'
  end

  private

  def set_user_and_post
    @user = current_user
    @post = @user.posts.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end

  def find_comment
    @comment = @post.comment

  def authorize_comment
    authorize! :destroy, @comment
  end
end






# app/controllers/comments_controller.rb
# class CommentsController < ApplicationController
#   before_action :find_comment, only: [:edit, :update, :destroy]
#   before_action :authorize_comment, only: [:edit, :update, :destroy]

#   # ...

#   def destroy
#     @comment.destroy
#     redirect_to post_path(@comment.post), notice: 'Comment was successfully destroyed.'
#   end

#   private

#   def authorize_comment
#     authorize! :destroy, @comment
#   end
# end

app/views/comments/comment.html.erb
<%= form_with(model: [current_user, @post.comments.build], local: true, class: 'new-comment-form') do |form| %>
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <%= form.submit "Create Comment", class: "btn btn-primary" %>
<% end %>

  

app/views/comments/new.html.erb
<%= form_with(model: [@user, @post, @comment], local: true, url: user_post_comments_path(@user, @post), method: :post, class: 'new-comment') do |f| %>
  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>