config/routes.rb
Rails.application.routes.draw do
  devise_for :users

 devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'sign_up', to: 'devise/registrations#new', as: :sign_up
  end

  root to: 'home#index'
  
  resources :users, only: [:index, :show, :new, :create] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :user_id, dependent: :destroy
  has_many :likes, foreign_key: :user_id, dependent: :destroy

  validates_uniqueness_of :name
  validates_uniqueness_of :email

  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.recent_posts(user_name, limit = 3)
    user = find_by(name: user_name)
    return unless user

    user.posts.order(created_at: :desc).limit(limit)
  end
end

app/models/users.rb
class Users < ApplicationRecord
    has_many :posts, foreign_key: :author_id, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
end
  

app/controllers/users_controller.rb
 class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show] 

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:comments).all
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>List of all User</h1>
<div class="container">
<% @users.each do |user| %>
  <div class="user_info">
    <div class="img">
    <%= image_tag user.photo, alt: "User Photo", class: "user-photo"%>
  </div>
  <div class="user">
    <h2><%= link_to user.name, user_path(user) %></h2>
    <p><strong>Number of Posts:</strong> <%= user.posts.count %></p>
  </div>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="main-container">
  <%= render partial: 'partials/userinfo', locals: { user: @user } %>
</div>
<div class="user-bio">
  <p><strong>Bio:</strong> <%= @user.bio %></p>
</div>

<div id="posts-container">
<% recent_posts = User.recent_posts(@user.name, 3).includes(:comments, :likes) %>
  <%= render partial: 'partials/post', collection: recent_posts %>
</div>

<div class="user-action-btns">
  <%= link_to 'Show more', user_posts_path(@user), class: "action-btn" %>
  <%= link_to 'Create a Post', new_user_post_path(@user), class: "action-btn" %>
</div>