config/routes.rb
Rails.application.routes.draw do
  devise_for :users

 devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'sign_up', to: 'devise/registrations#new', as: :sign_up
  end

  root to: 'home#index'
  
  resources :users, only: [:index, :show, :new, :create] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :author_id
  has_many :comments, foreign_key: :post_id, dependent: :destroy
  has_many :likes, foreign_key: :post_id, dependent: :destroy

  after_create :increment_user_posts_counter
  after_destroy :decrement_user_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  private

  def increment_user_posts_counter
    user.increment(:posts_counter).save
  end

  def decrement_user_posts_counter
    user.decrement(:posts_counter).save
  end

  public

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def update_likes_counter
    update(likes_counter: likes.count)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user, only: %i[index show new create]
  before_action :set_post, only: [:index, :show, :new, :destroy]
  before_action :authorize_post, only: [:destroy]

  def index
    @posts = @user.posts.includes(:comments).paginate(page: params[:page], per_page: 2)
  end

  def show
    @like = Like.new
  end

  def new
    @post = @user.posts.new
  end

  def create
    @post = @user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Post saved successfully'
      redirect_to user_posts_path(@user)
    else
      flash[:error] = 'Error: Post could not be saved'
      flash[:error_details] = @post.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post deleted successfully'
    redirect_to user_posts_path(@user)
  end

  private

  def set_user
    @user = current_user
  end

  def set_post
    @post = @user.posts.find(params[:id])
  end

  def authorize_post
    authorize! :manage, @post
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end


# class PostsController < ApplicationController
#   before_action :set_user, only: %i[index show new create]
#   before_action :set_post, only: [:show]

#   def index
#     @posts = @user.posts.includes(:comments).paginate(page: params[:page], per_page: 2)
#   end

#   def show
#     @post = @user.posts.includes(:comments).find(params[:id])
#     @like = Like.new
#   end

#   def new
#     @post = @user.posts.new
#   end

#   def create
#     @post = @user.posts.build(post_params)

#     if @post.save
#       flash[:success] = 'Post saved successfully'
#       redirect_to user_posts_path(@user)
#     else
#       flash[:error] = 'Error: Post could not be saved'
#       flash[:error_details] = @post.errors.full_messages.join(', ')
#       render :new
#     end
#   end

#   private

#   def set_user
#     @user = current_user
#   end

#   def set_post
#     @post = @user.posts.find(params[:id])
#   end

#   def post_params
#     params.require(:post).permit(:title, :text)
#   end
# end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="main-container">
    <%= render partial: 'partials/userinfo', locals: { user: @user} %>
</div>
<div class="posts-container">
  <% @posts.each do |post| %>
    <%= link_to user_post_path(@user, post), id: "user_#{post.id}", class: 'posts-container' do %> 
      <%= render partial: 'partials/post', locals: { post: post } %>
    <% end %>
    <ul class="comments-container">
      <% if post.comments.present? %>
        <% recent_comments = post.comments.order(created_at: :desc).limit(2) %>
        <% recent_comments.each do |comment| %> 
          <li class="user-comment"><%= comment.user.name %>: <%= comment.text %></li>
        <% end %>
      <% else %>
        <li class="user-comments">No comments for this post.</li>
      <% end %>
    </ul>

  <% end %>
</div>
<div class="pagination">
  <%= link_to 'Pagination', user_posts_path(@user, page: @posts.current_page + 1), class: 'pagination-btn' %>
  <%= link_to 'Create a Post', new_user_post_path(@user), class: "action-btn" %>
</div>

app/views/posts/new.html.erb
<%= form_with model: [@user, @post], url: user_posts_path(@user), class: "new-post", method: :post do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <%= f.submit "Create new post", class: "btn btn-primary"  %>
<% end %>

app/views/posts/show.html.erb
<div class="main-container">
  <div class="post-info">
    <h3 class="post-id-username">Post <%= @post.title %> by <%= @user.name %></h3>
    <p class="post-comments-likes">Comments: <%= @post.comments.count %>, Likes: <%= @post.likes.count %></p>       
  </div>
  <div class="post-text">
    <%= @post.text %>
  </div>
</div>

<ul class="comments-container">
  <% if @post.comments.present? %>
    <% recent_comments = @post.comments.order(created_at: :desc).limit(3) %>
      <% recent_comments.each do |comment| %> 
      <li class="user-comment">
        <%= comment.user.name %>: <%= comment.text %>
        <% if can? :destroy, comment %>
          <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% end %>
      </li>
    <% end %>
  <% else %>
    <li class="user-comments">No comments for this post.</li>
  <% end %>
</ul>

<div class="post-action-btns">
  <%= render 'likes/new', post: @post, like: @like %>
  <%= link_to 'Comment', new_user_post_comment_path(@user, @post), class: "comment-btn" %>
</div>